version: 0.2
env:
  parameter-store:
    # LOGIN:   SONAR_TOKEN
    # HOST:    HOST
    # Organization: Organization
    # Project: Project
    CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto17  # You can use "8" if you prefer Java 8
  pre_build:
    commands:
      - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
  build:
    commands:
      - mvn clean install
      - mvn -X sonar:sonar -Dsonar.projectKey=aws-native-cicd-pipeline-project -Dsonar.organization=mbandi-aak-aws-devops-org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=8260e159660ec86a7d43c6764764762b1ab0c736
  post_build:
    commands:
      # Any post-build commands you need to execute

artifacts:
  files: '**/*'
